version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v0-container-service-yarn-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v0-container-service-yarn-cache-{{ checksum "yarn.lock" }}
        
      - run: yarn ci


